# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcapi.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgrpcapi.proto\x12\x07\x66\x61stapi\"\x83\x04\n\x06\x44ocObj\x12\x12\n\narticle_id\x18\x01 \x01(\x03\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\t\x12\x1b\n\x04lang\x18\x05 \x01(\x0e\x32\r.fastapi.Lang\x12+\n\tlocations\x18\x06 \x03(\x0b\x32\x18.fastapi.DocObj.Location\x12/\n\x0fsemantic_vector\x18\x07 \x03(\x0b\x32\x16.fastapi.DocObj.Vector\x12)\n\x08keywords\x18\x08 \x03(\x0b\x32\x17.fastapi.DocObj.Keyword\x12(\n\x08\x65ntities\x18\t \x03(\x0b\x32\x16.fastapi.DocObj.Entity\x12%\n\x06themes\x18\n \x03(\x0b\x32\x15.fastapi.DocObj.Theme\x12%\n\x06_class\x18\x0b \x03(\x0b\x32\x15.fastapi.DocObj.Class\x1a$\n\x08Location\x12\x0b\n\x03lat\x18\x01 \x01(\x02\x12\x0b\n\x03lon\x18\x02 \x01(\x02\x1a\x17\n\x06Vector\x12\r\n\x05value\x18\x01 \x01(\x02\x1a\x17\n\x07Keyword\x12\x0c\n\x04name\x18\x01 \x01(\t\x1a\x16\n\x06\x45ntity\x12\x0c\n\x04name\x18\x01 \x01(\t\x1a\x15\n\x05Theme\x12\x0c\n\x04name\x18\x01 \x01(\t\x1a\x15\n\x05\x43lass\x12\x0c\n\x04name\x18\x01 \x01(\t*\x16\n\x04Lang\x12\x06\n\x02RU\x10\x00\x12\x06\n\x02\x45N\x10\x01\x32\x36\n\x05Saver\x12-\n\x07SaveDoc\x12\x0f.fastapi.DocObj\x1a\x0f.fastapi.DocObj\"\x00\x42\x30\n\x18io.grpc.examples.fastapiB\x0cGrpcApiProtoP\x01\xa2\x02\x03RTGb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpcapi_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030io.grpc.examples.fastapiB\014GrpcApiProtoP\001\242\002\003RTG'
  _LANG._serialized_start=544
  _LANG._serialized_end=566
  _DOCOBJ._serialized_start=27
  _DOCOBJ._serialized_end=542
  _DOCOBJ_LOCATION._serialized_start=386
  _DOCOBJ_LOCATION._serialized_end=422
  _DOCOBJ_VECTOR._serialized_start=424
  _DOCOBJ_VECTOR._serialized_end=447
  _DOCOBJ_KEYWORD._serialized_start=449
  _DOCOBJ_KEYWORD._serialized_end=472
  _DOCOBJ_ENTITY._serialized_start=474
  _DOCOBJ_ENTITY._serialized_end=496
  _DOCOBJ_THEME._serialized_start=498
  _DOCOBJ_THEME._serialized_end=519
  _DOCOBJ_CLASS._serialized_start=521
  _DOCOBJ_CLASS._serialized_end=542
  _SAVER._serialized_start=568
  _SAVER._serialized_end=622
# @@protoc_insertion_point(module_scope)
